name: GrandTheftCars
main: me.lawhit.gtc.Main
version: 0.1
description: Drivecars
author: lawhit
commands:
    createcar:
        description: sucksdick
    createstore:
        description: sucksdick
    createphone:
        description: sucksdick
depend: [Vault,RemoteEntities,ProtocolLib]