name: GrandTheftCars
main: me.lawhit.gtc.Main
version: 0.1
description: Drivecars
author: lawhit
commands:
    createcar:
        description: Creates a car.
    createstore:
        description: Creates a Store
    createphone:
        description: Creates a phone.
depend: [Vault,ProtocolLib,CrackShot]
softdepend: [Aconomy]
